apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent-lab3
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: node
      image: node:24-alpine
      command:
        - /bin/sh
        - -c
      args:
        - cat
      tty: true
      workingDir: /home/jenkins/agent

    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.21.0-debug
      command:
        - /busybox/sh
        - -c
      args:
        - tail -f /dev/null
      workingDir: /home/jenkins/agent

    - name: kubectl
      image: alpine/k8s:1.37.0
      command:
        - /bin/sh
        - -c
      args:
        - tail -f /dev/null
      workingDir: /home/jenkins/agent

    - name: skopeo
      image: quay.io/skopeo/stable:latest
      command:
        - /bin/sh
        - -c
      args:
        - tail -f /dev/null
      workingDir: /home/jenkins/agent
